#include <Windows.h>
#pragma once
namespace Agony
{
	public enum class WoWObjectType : signed char
	{
		Object = 0,
		Item = 1,
		Container = 2,
		AzeriteEmpoweredItem = 3,
		AzeriteItem = 4,
		Unit = 5,
		Player = 6,
		ActivePlayer = 7,
		GameObject = 8,
		DynamicObject = 9,
		Corpse = 10,
		AreaTrigger = 11,
		Scene = 12,
		Conversation = 13,
		AIGroup = 14,
		Scenario = 15,
		Loot = 16,
		Invalid = 17,
	};

	public enum class UnitRaceId : signed char
	{
		Invalid = 0,
		Human = 1,
		Orc = 2,
		Dwarf = 3,
		NightElf = 4,
		Undead = 5,
		Tauren = 6,
		Gnome = 7,
		Troll = 8,
		Goblin = 9,
		BloodElf = 10,
		Draenei = 11,
		FelOrc = 12,
		Naga = 13,
		Broken = 14,
		Skeleton = 15,
		Vrykul = 16,
		Tuskarr = 17,
		ForestTroll = 18,
		Taunka = 19,
		NorthrendSkeleton = 20,
		IceTroll = 21,
		Worgen = 22,
		Gilnean = 23,
		PandarenNeutral = 24,
		PandarenAlliance = 25,
		PandarenHorde = 26,
		Nightborne = 27,
		HighmountainTauren = 28,
		VoidElf = 29,
		LightforgedDraenei = 30,
		ZandalariTroll = 31,
		KulTiran = 32,
		ThinHuman = 33,
		DarkIronDwarf = 34,
		Vulpera = 35,
		MagharOrc = 36,
		Mechagnome = 37
	};

	public enum class UnitClassId : signed char
	{
		Invalid = 0,
		Warrior = 1,
		Paladin = 2,
		Hunter = 3,
		Rogue = 4,
		Priest = 5,
		DeathKnight = 6,
		Shaman = 7,
		Mage = 8,
		Warlock = 9,
		Monk = 10,
		Druid = 11,
		DemonHunter = 12
	};

	public enum class GuidType
	{
		GuidTypeNone = 0,
		GuidTypeUniq = 1,
		GuidTypePlayer = 2,
		GuidTypeItem = 3,
		GuidTypeWorldTransaction = 4,
		GuidTypeStaticDoor = 5,
		GuidTypeTransport = 6,
		GuidTypeConversation = 7,
		GuidTypeCreature = 8,
		GuidTypeVehicle = 9,
		GuidTypePet = 10,
		GuidTypeGameObject = 11,
		GuidTypeDynamicObject = 12,
		GuidTypeAreaTrigger = 13,
		GuidTypeCorpse = 14,
		GuidTypeLootObject = 15,
		GuidTypeSceneObject = 16,
		GuidTypeScenario = 17,
		GuidTypeAIGroup = 18,
		GuidTypeDynamicDoor = 19,
		GuidTypeClientActor = 20,
		GuidTypeVignette = 21,
		GuidTypeCallForHelp = 22,
		GuidTypeAIResource = 23,
		GuidTypeAILock = 24,
		GuidTypeAILockTicket = 25,
		GuidTypeChatChannel = 26,
		GuidTypeParty = 27,
		GuidTypeGuild = 28,
		GuidTypeWowAccount = 29,
		GuidTypeBNetAccount = 30,
		GuidTypeGMTask = 31,
		GuidTypeMobileSession = 32,
		GuidTypeRaidGroup = 33,
		GuidTypeSpell = 34,
		GuidTypeMail = 35,
		GuidTypeWebObj = 36,
		GuidTypeLFGObject = 37,
		GuidTypeLFGList = 38,
		GuidTypeUserRouter = 39,
		GuidTypePVPQueueGroup = 40,
		GuidTypeUserClient = 41,
		GuidTypePetBattle = 42,
		GuidTypeUniqUserClient = 43,
		GuidTypeBattlePet = 44,
		GuidTypeCommerceObj = 45,
		GuidTypeClientSession = 46,
		GuidTypeCast = 47,
		Invalid = 48
	};
}